What's pytorch

Pytorch官方对自己的定义有两个：
1. GPU环境下的Numpy替代方案
2. 灵活高效的深度学习研究平台

在Python语言环境下，Pytorch与TensorFlow相比确实更受学术界的青睐，因为它使用起来更加方便，学习门槛较低，学者们能够快速地用Pytorch复现文件中的算法，而TensorFlow更像是一个工业产品，学习起来就像是一门新的语言。

Pytorch的使用方式与Numpy十分相似。

In [16]:
import torch
x = torch.empty(5,3) # 未进行初始化的5×3张量
x

tensor(1.00000e-36 *
       [[ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 2.5571,  0.0000,  0.0000],
        [ 0.0000,  0.0001,  0.0000],
        [ 2.5574,  0.0000,  0.0000]])

随机数

In [17]:
torch.rand(5,3)

tensor([[ 0.2444,  0.6785,  0.2451],
        [ 0.9132,  0.8451,  0.5834],
        [ 0.7033,  0.6024,  0.2291],
        [ 0.4887,  0.4893,  0.2217],
        [ 0.0195,  0.3566,  0.0274]])

初始化张量

In [18]:
torch.zeros(5,3,dtype=torch.long)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])

In [19]:
torch.tensor([5.5,3])

tensor([ 5.5000,  3.0000])

基于现有张量创建新的张量

In [21]:
x = x.new_ones(5,3,dtype=torch.double) # 修改了size和dtype
print(x)
x = torch.randn_like(x,dtype=torch.float) # 修改了dtype，按x的size生成随机数
print(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)
tensor([[-1.4235,  0.4799,  0.0361],
        [-1.4761, -0.5444,  0.2960],
        [-1.2031, -0.0779, -0.3780],
        [-0.5176,  0.7639, -1.2734],
        [-0.3884, -2.3110, -0.1082]])


In [25]:
len(x.size()),x.size()

(2, torch.Size([5, 3]))

张量操作

加

In [26]:
y = torch.rand(5,3)
x + y

tensor([[-0.5875,  0.9132,  0.7143],
        [-0.5366,  0.0159,  0.3394],
        [-0.9254, -0.0055,  0.4600],
        [ 0.3133,  1.4835, -0.7862],
        [ 0.3037, -2.0038,  0.2145]])

In [27]:
torch.add(x,y)

tensor([[-0.5875,  0.9132,  0.7143],
        [-0.5366,  0.0159,  0.3394],
        [-0.9254, -0.0055,  0.4600],
        [ 0.3133,  1.4835, -0.7862],
        [ 0.3037, -2.0038,  0.2145]])

In [28]:
result = torch.empty(5, 3) # 用于接受加法运算的结果
torch.add(x, y, out=result)
result

tensor([[-0.5875,  0.9132,  0.7143],
        [-0.5366,  0.0159,  0.3394],
        [-0.9254, -0.0055,  0.4600],
        [ 0.3133,  1.4835, -0.7862],
        [ 0.3037, -2.0038,  0.2145]])

In [29]:
y.add_(x) # in_place 运算
y

tensor([[-0.5875,  0.9132,  0.7143],
        [-0.5366,  0.0159,  0.3394],
        [-0.9254, -0.0055,  0.4600],
        [ 0.3133,  1.4835, -0.7862],
        [ 0.3037, -2.0038,  0.2145]])

张量切片

In [30]:
y[:,2]

tensor([ 0.7143,  0.3394,  0.4600, -0.7862,  0.2145])

In [31]:
x = torch.randn(4,4)
print(x.size())
y = x.view(16)
print(y.size())
z = x.view(-1,8)
print(z.size())

torch.Size([4, 4])
torch.Size([16])
torch.Size([2, 8])


张量中只有一个变量时，尅使用.item()方法获取其值

In [36]:
a = x[1,1]
a.item()

0.38785359263420105

Numpy和Pytorch的互转

既然号称Numpy的GPU替代方案，自然能够接受Numpy的数据格式

In [37]:
a = torch.ones(5)
a

tensor([ 1.,  1.,  1.,  1.,  1.])

In [40]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [41]:
torch.from_numpy(b)

tensor([ 1.,  1.,  1.,  1.,  1.])

将张量传入CUDA

In [45]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x,device=device)
    x = x.to(device)
    z = x + y
    print("cuda",z)
else:
    device = torch.device("cpu")
    y = torch.ones_like(x,device=device)
    x = x.to(device)
    z = x + y
    print("cpu",z)

cpu tensor([[ 0.7775,  0.6410,  0.1183,  1.2720],
        [ 2.0208,  1.3879,  0.6263, -0.5373],
        [ 2.3479,  0.9108,  1.0894,  1.2364],
        [-0.4528,  2.3589,  2.4318,  1.3387]])
